//------------------Promise Practice


//console.log('Starting')
const addasyncFunction = (a,b)=>{

  //write code to return a promise that waits for 2 seconds and 
  // gives sum of two numbers a & b
  // if a and b are positive else throws error 
  

}



addasyncFunction(1 , 2)  // this will return 'result: 3'
.then((result)=>{console.log('result: ', result)})  
.catch((err)=>{console.log('error: ', err)})

//console.log('Ending')